# Generated by Django 2.2.3 on 2019-08-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=49, null=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'db_table': 'banks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('address', models.CharField(blank=True, max_length=195, null=True)),
                ('branch', models.CharField(blank=True, max_length=74, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=26, null=True)),
            ],
            options={
                'verbose_name': 'Bank Branch',
                'verbose_name_plural': 'Bank Branches',
                'db_table': 'branches',
                'managed': False,
            },
        ),
    ]
